//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.14

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "git_commit")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub uid: Uuid,
    pub repo_uid: Uuid,
    pub refs_uid: Uuid,
    pub commit_id: String,
    pub tree: String,
    pub parents_id: Json,
    pub author: Option<Uuid>,
    pub committer: Option<Uuid>,
    #[sea_orm(column_type = "Text", nullable)]
    pub content: String,
    pub time: i64,
    pub offset: i32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
