//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.14

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "git_tag")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub uid: Uuid,
    pub repo_uid: Uuid,
    pub tag_id: String,
    pub tag_name: String,
    pub tagger: Option<Uuid>,
    pub message: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
