//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.14

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "git_repo")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub uid: Uuid,
    pub namespace: String,
    #[sea_orm(column_type = "Text")]
    pub repo_name: String,
    pub default_head: String,
    pub description: Option<String>,
    pub is_private: bool,
    pub created_at: DateTime,
    pub updated_at: DateTime,
    pub storage: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}

impl Model {
    pub fn to_path(&self) -> String {
        self.uid.to_string()
    }
}
