http:
  port: 80
  host: 0.0.0.0
  ssl: false
  cert: null
  key: null
  server: actix
postgres:
  host: 47.236.139.99
  port: '6444'
  user: postgres
  password: D8Sl659hBP
  dbname: gitdata
  schema: public
  pool_size: 10
  max_conn_lifetime: 60
  max_conn_lifetime_ms: 60000
  idle_timeout: 60
  connect_timeout: 10
  max_connections: 20
  min_connections: 5
  log_level: debug
redis:
  host: 122.11.28.208
  port: 6379
  password: null
  db: 0
  pool_size: 10
mongodb:
  host: 122.11.28.208
  port: 27017
  username: 'root'
  password: '1313113a'
  database: ''
  auth_db: ''
  pool_size: 2000
email:
  smtp: smtp.exmail.qq.com
  port: 465
  username: gitdata-bot@gitdata.ai
  password: 'GsMKT8AP5xf6RUGq'
  from: gitdata-bot@gitdata.ai
