version: '3.8'
services:

  jz_dragonfly:
    image: 'docker.dragonflydb.io/dragonflydb/dragonfly'
    ulimits:
      memlock: -1
    volumes:
      - dragonflydata:/data
    restart: always

  jz_postgres:
    container_name: postgres
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123456
      - PGDATA=/data/postgres
    volumes:
      - postgres:/data/postgres
    restart: always
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d postgres" ]
      interval: 30s
      timeout: 10s
      retries: 5
  jzfs:
    image: docker.io/gitdatateam/gitdataos:latest
    environment:
      - PORT=9000
      - DATABASE_URL=postgres://postgres:123456@jz_postgres:5432/postgres
      - ED25519=242,51,52,209,248,10,134,56,11,3,124,253,143,98,54,239,228,197,217,186,187,56,0,39,81,222,5,110,129,246,41,155,233,136,95,15,240,137,29,234,201,164,157,102,108,239,119,217,208,163,248,253,237,229,183,17,106,216,164,255,151,65,219,235
      - SMTP_PASSWORD=****
      - SMTP_USERNAME=****
      - REDIS_URL=redis://jz_dragonfly:6379/0
    volumes:
      - jzfs_repo:/app/data/00000000-0000-0000-0000-000000000000
      - jzfs_static:/app/data/static
    restart: always
    depends_on:
      - jz_postgres
      - jz_dragonfly
  jzfs-ui:
    image: docker.io/gitdatateam/gitdataweb:latest
    depends_on:
      - jzfs

  jz_proxy:
    image: docker.io/gitdatateam/proxy:latest
    ports:
      - "8080:80"
      - "8022:22"
    depends_on:
      - jzfs
      - jzfs-ui


volumes:
  dragonflydata:
  postgres:
  jzfs_repo:
  jzfs_static: