apiVersion: v1
kind: Service
metadata:
  name: jzfs-git-ssh-service
  namespace: gitdata
  labels:
    apptype: jzfs-git-ssh
spec:
  type: ClusterIP
  selector:
    app: jzfs-git-ssh
  ports:
    - protocol: TCP
      port: 22
      targetPort: 22
