apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: gitdata
  name: jzfs-api
  labels:
    apptype: jzfs-api
spec:
  replicas: {{ .Values.replicas}}
  selector:
    matchLabels:
      app: jzfs-api
  template:
    metadata:
      labels:
        app: jzfs-api
        apptype: jzfs-api
    spec:
      containers:
        - name: jzfs-rust
          image: "gitdatateam/jzfs-api:{{ .Values.tag }}"
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          volumeMounts:
            - mountPath: /exports
              name: shared-storage
            - mountPath: /static
              name: static-storage
          env:
            - name: NACOS_ADDR
              valueFrom: {{ .Values.nacos.addr }}
            - name: NACOS_PASSWORD
              valueFrom: {{ .Values.nacos.passwd }}
            - name: NACOS_NAMESPACE
              valueFrom: {{ .Values.nacos.namespace }}
            - name: NACOS_USER
              valueFrom: {{ .Values.nacos.user }}
      volumes:
        - name: shared-storage
          hostPath:
            path: /exports
            type: Directory

        - name: static-storage
          hostPath:
            path: /static
            type: Directory