apiVersion: v1
kind: Service
metadata:
  name: gitdataos-svc
  namespace: gitdata
  labels:
    helm.sh/chart: gitdataos-0.1.0
    app.kubernetes.io/name: gitdataos
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/version: "1.30.0"
    app.kubernetes.io/managed-by: Helm
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: gitdataos
    app.kubernetes.io/instance: release-name

---
apiVersion: v1
kind: Service
metadata:
  name: gitdataos-ssh-svc
  namespace: gitdata
  labels:
    helm.sh/chart: gitdataos-0.1.0
    app.kubernetes.io/name: gitdataos
    app.kubernetes.io/version: "1.30.0"
    app.kubernetes.io/managed-by: Helm
spec:
  type: NodePort
  ports:
    - port: 30322
      targetPort: 30322
      protocol: TCP
      name: ssh
      nodePort: 30322
  selector:
    app.kubernetes.io/name: gitdataos-ssh
