[package]
name = "lib-mq"
version.workspace = true
edition.workspace = true
authors.workspace = true
homepage.workspace = true



[[bin]]
path = "src/bin/mq.rs"
name = "gitdata-mq"


[dependencies]
tokio = { version = "1.43.0", features = ["full"] }
dashmap = { version = "6.1.0", features = ["rayon"] }
lib-config = { workspace = true }
lib-entity = { workspace = true }
serde = { version = "1.0.217", features = ["derive"] }
serde_json = "1.0.138"
tracing-subscriber = "0.3.19"
log = "0.4.25"
rand = "0.9.0"
rdkafka = { version = "0.37.0", features = ["cmake-build"] }
futures-util = "0.3.31"
lettre = {version = "0.11.10",features = [
    "smtp-transport",
    "serde",
    "rustls-tls",
    "rustls-native-certs",
    "hostname",
    "tokio1",
    "tokio1-rustls-tls",
    "tokio1-native-tls"
]}
uuid = { version = "1.12.1", features = ["v4"] }
