//! `SeaORM` Migration, @generated by sea-orm-cli 1.1.14

use sea_orm_migration::prelude::*;

#[derive(DeriveMigrationName)]
pub struct Migration;

#[async_trait::async_trait]
impl MigrationTrait for Migration {
    async fn up(&self, manager: &SchemaManager) -> Result<(), DbErr> {
        // 删除git_refs表中的is_private字段
        manager
            .alter_table(
                Table::alter()
                    .table(GitRefs::Table)
                    .drop_column(GitRefs::IsPrivate)
                    .to_owned(),
            )
            .await
    }

    async fn down(&self, manager: &SchemaManager) -> Result<(), DbErr> {
        // 重新添加is_private字段
        manager
            .alter_table(
                Table::alter()
                    .table(GitRefs::Table)
                    .add_column(
                        ColumnDef::new(GitRefs::IsPrivate)
                            .boolean()
                            .not_null()
                            .default(false),
                    )
                    .to_owned(),
            )
            .await
    }
}

#[derive(Iden)]
enum GitRefs {
    Table,
    IsPrivate,
}
