# Default values for charts.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1
namespace: gitdata
config: gitdataos-configmap
image:
  repository: gitdatateam/gitdataos
  pullPolicy: IfNotPresent
  tag: latest

imagePullSecrets: []
nameOverride: "gitdataos"
fullnameOverride: "gitdataos"

serviceAccount:
  create: true
  annotations: {}
  name: "gitdataos"

podAnnotations: {}

podSecurityContext: {}

securityContext: {}


service:
  type: ClusterIP
  port: 80
  targetPort: 80

resources:
   limits:
     memory: 8Gi
   requests:
     memory: 2Gi

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}
volumeMounts:
  - mountPath: /app/data/00000000-0000-0000-0000-000000000000
    name: shared-storage
  - mountPath: /app/data/static
    name: static-storage

volumes:
  - name: shared-storage
    hostPath:
      path: /exports
      type: Directory

  - name: static-storage
    hostPath:
      path: /static
      type: Directory