apiVersion: v1
kind: Service
metadata:
  name: jzfs-api-service
  namespace: gitdata
  labels:
    apptype: jzfs-api
spec:
  type: ClusterIP
  selector:
    app: jzfs-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80