apiVersion: v1
kind: Service
metadata:
  name: gateway-service
  namespace: {{ .Values.namespace }}
  labels:
    apptype: gateway
spec:
  type: ClusterIP
  selector:
    app: gateway
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: gitdata-auth-service
  labels:
    app: gitdata-auth
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  selector:
    app: gitdata-auth
