[package]
name = "endpoint"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
description.workspace = true
keywords.workspace = true
readme.workspace = true
homepage.workspace = true
documentation.workspace = true
publish.workspace = true

[dependencies]
workhorse = { workspace = true }
cert = { workspace = true }
authd = { workspace = true }

session = { workspace = true, features = [] }
sea-orm = { workspace = true, features = ["uuid","chrono","sqlx-all", "pgvector"] }
serde = { workspace = true, features = ["derive"] }
chrono = { workspace = true, features = ["clock"] }
uuid = { workspace = true, features = ["v7","v4","serde"] }
tarpc = { workspace = true, features = ["full"] }
async-nats = { workspace = true, features = [] }
sha256 = { workspace = true }
rand = { workspace = true, features = ["std_rng"] }
serde_json = { workspace = true }
tokio = { workspace = true, features = ["full"]}
actix-web = { workspace = true, features = ["cookies"] }
web-session = { workspace = true }
tracing = { workspace = true }
woothee = "0.13.0"

[features]
default = ["distributed"]
distributed = []
local = []