version: '3'
services:
    zookeeper:
        image: zookeeper
        ports:
            - "2182:2181"
        networks:
            - kafka_network
        restart: always

    kafka1:
        image: wurstmeister/kafka
        container_name: kafka1
        ports:
            - "9093:9092"
        environment:
            KAFKA_BROKER_ID: 0
            KAFKA_NUM_PARTITIONS: 3
            KAFKA_DEFAULT_REPLICATION_FACTOR: 2
            KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
            KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
            KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://24.233.1.196:9093
        volumes:
            - /data/docker-compose/kafka/broker1/logs:/opt/kafka/logs
        networks:
            - kafka_network
        restart: always

    kafka2:
        image: wurstmeister/kafka
        container_name: kafka2
        ports:
            - "9094:9092"
        environment:
            KAFKA_BROKER_ID: 1
            KAFKA_NUM_PARTITIONS: 3
            KAFKA_DEFAULT_REPLICATION_FACTOR: 2
            KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
            KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
            KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://24.233.1.196:9094
        volumes:
            - /data/docker-compose/kafka/broker2/logs:/opt/kafka/logs
        networks:
            - kafka_network
        restart: always

    kafka3:
        image: wurstmeister/kafka
        container_name: kafka3
        ports:
            - "9095:9092"
        environment:
            KAFKA_BROKER_ID: 2
            KAFKA_NUM_PARTITIONS: 3
            KAFKA_DEFAULT_REPLICATION_FACTOR: 2
            KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
            KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
            KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://24.233.1.196:9095
        volumes:
            - /data/docker-compose/kafka/broker3/logs:/opt/kafka/logs
        networks:
            - kafka_network
        restart: always

    kafka_ui:
        image: lcc1024/kafka_ui_lcc:1.0
        container_name: kafka_ui
        ports:
            - "8093:8093"
        environment:
            ZOOKEEPER_HOST: zookeeper
            ZOOKEEPER_PORT: 2181
            JMX_HOSTS: kafka1,kafka2,kafka3
            JMX_PORTS: 9502,9502,9502
            KAFKA_HOSTS: kafka1,kafka2,kafka3
            KAFKA_PORTS: 9092,9092,9092
        networks:
            - kafka_network
        restart: always

networks:
    kafka_network:
        driver: bridge
