[package]
name = "prollytree"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
description.workspace = true
keywords.workspace = true
readme.workspace = true
homepage.workspace = true
documentation.workspace = true
publish.workspace = true

[dependencies]
rust-i18n = { workspace = true, features = [] }
serde = { workspace = true, features = ["derive"] }
crossbeam = { workspace = true, features = [] }
sha1 = { version = "0.10.6", features = ["oid"] }
hex = "0.4.3"