apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "gitdataai.serviceAccountName" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{ include "gitdataai.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{ toYaml . | nindent 4 }}
  {{- end }}