[package]
name = "error"
version = "0.1.0"
edition = "2024"

[dependencies]
git2 = "0.20.2"
redis = "0.32.5"
sea-orm = "1.1.14"
tokio = "1.47.1"
anyhow = "1.0.98"
serde = { version = "1.0.219", features = ["derive"] }
toml = "0.9.5"
serde_json = "1.0.142"

actix-web = "4.11.0"