name: Build

on:
  workflow_call:

jobs:
  build:
    name: Build
    runs-on: [self-hosted]

    steps:
      - name: Print Event
        run: |
          echo "Event Name: ${{ github.event_name }}"
          echo "Repository: ${{ github.repository }}"
          echo "SHA: ${{ github.sha }}"
          echo "Ref: ${{ github.ref }}"
          echo "Action: ${{ github.action }}"
          echo "Actor: ${{ github.actor }}"
          echo "Workflow Run ID: ${{ github.run_id }}"
          echo "Head Repository: ${{ github.head_repository }}"
          echo "Base Repository: ${{ github.base_repository }}"

      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install latest nightly
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          override: true
          components:

      - name: Build project
        run: |
          export ALL_PORT=80
          cargo build --release --workspace

      - name: Get version
        id: version
        run: |
          if [[ -n "$GITHUB_REF" && "$GITHUB_REF" == "refs/tags/"* ]]; then
            echo "tag version"
            echo "::set-output name=version::${GITHUB_REF/refs\/tags\//}"
          else
            echo "commit version"
            echo "::set-output name=version::${{ github.sha }}"
          fi

      - name: Build nad Push Migrator
        run: |
          docker build -t gitdatateam/migrator:${{ steps.version.outputs.version }} -f ./docker/migrator.Dockerfile .
          docker push gitdatateam/migrator:${{ steps.version.outputs.version }}

      - name: Build and Push Gateway
        run: |
          docker build -t gitdatateam/gateway:${{ steps.version.outputs.version }} -f ./docker/gateway.Dockerfile .
          docker push gitdatateam/gateway:${{ steps.version.outputs.version }}

      - name: Build and Push GitdataAuth
        run: |
          docker build -t gitdatateam/gitdata-auth:${{ steps.version.outputs.version }} -f ./docker/auth.Dockerfile .
          docker push gitdatateam/gitdata-auth:${{ steps.version.outputs.version }}

      - name: Build and Push GitdataMQ
        run: |
          docker build -t gitdatateam/gitdata-mq:${{ steps.version.outputs.version }} -f ./docker/mq.Dockerfile .
          docker push gitdatateam/gitdata-mq:${{ steps.version.outputs.version }}

      - name: Build and Push GitdataUser
        run: |
          docker build -t gitdatateam/gitdata-user:${{ steps.version.outputs.version }} -f ./docker/user.Dockerfile .
          docker push gitdatateam/gitdata-user:${{ steps.version.outputs.version }}


