name: test

on:
    workflow_call:
        secrets:
            KUBECONTENT:
                required: true
            NACOS:
                required: true
jobs:
    deployment:
        if: ${{ startsWith(github.ref, 'refs/heads/deployment/') || github.ref == 'refs/heads/main'  }}
        runs-on: [self-hosted]
        steps:
            - name: Checkout repo
              uses: actions/checkout@v3

            - name: Deploy
              uses: WyriHaximus/github-action-helm3@v3
              with:
                  exec: /usr/sbin/helm upgrade gateway --install ./deploy/gitdata --namespace gitdataai --set-string nacos=${{ secrets.NACOS }}  --set-string tag=${{ steps.version.outputs.version }}
                  kubeconfig: ${{ secrets.KUBECONTENT }}
                  overrule_existing_kubeconfig: 'true'
