name: test

on:
    workflow_call:
        secrets:
            KUBECONTENT:
                required: true
jobs:
    deployment:
        if: ${{ startsWith(github.ref, 'refs/heads/deployment/') || github.ref == 'refs/heads/main'  }}
        runs-on: [self-hosted]
        steps:
            - name: Checkout repo
              uses: actions/checkout@v3

            - name: Get version
              id: version
              run: |
                if [[ -n "$GITHUB_REF" && "$GITHUB_REF" == "refs/tags/"* ]]; then
                  echo "tag version"
                  echo "::set-output name=version::${GITHUB_REF/refs\/tags\//}"
                else
                  echo "commit version"
                  echo "::set-output name=version::${{ github.sha }}"
                fi
            - name: Set up Helm
              run: |
                curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash

            - name: DeployOs
              uses: WyriHaximus/github-action-helm3@v3
              with:
                  exec: /usr/local/bin/helm upgrade gitdataos --install ./charts --namespace gitdata --set image.tag=${{ steps.version.outputs.version }}
                  kubeconfig: ${{ secrets.KUBECONTENT }}
                  overrule_existing_kubeconfig: 'true'
