name: Build and Push Frontend with GitHub Actions

on:
  workflow_call:
    secrets:
      DOCKER_USERNAME:
        required: true
      DOCKER_PASSWORD:
        required: true

jobs:
  build:
    name: Build Frontend
    runs-on: [self-hosted]
    outputs:
      version: "${{ steps.version.outputs.version }}"

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Print Event
        run: |
          echo "Event Name: ${{ github.event_name }}"
          echo "Repository: ${{ github.repository }}"
          echo "SHA: ${{ github.sha }}"
          echo "Ref: ${{ github.ref }}"
          echo "Action: ${{ github.action }}"
          echo "Actor: ${{ github.actor }}"
          echo "Workflow Run ID: ${{ github.run_id }}"
          echo "Head Repository: ${{ github.head_repository }}"
          echo "Base Repository: ${{ github.base_repository }}"

      - name: Get version
        id: version
        run: |
          if [[ -n "$GITHUB_REF" && "$GITHUB_REF" == "refs/tags/"* ]]; then
            echo "tag version"
            echo "::set-output name=version::${GITHUB_REF/refs\/tags\//}"
          else
            echo "commit version"
            echo "::set-output name=version::${{ github.sha }}"
          fi

  

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10

      - name: Install Node.js and pnpm
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      - name: Install project dependencies and build
        run: |
          cd vite-project \
          && pnpm install \
          && pnpm run build \
          && cd ..

      - name: Docker Login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and Push GitDataWeb
        uses: docker/build-push-action@v4
        with:
          tags: |
            gitdatateam/gitdataweb:${{ steps.version.outputs.version }}
            gitdatateam/gitdataweb:latest
          push: true
          cache-from: type=gha
          file: ./vite-project/Dockerfile
          cache-to: type=gha,mode=max
          platforms: linux/amd64
          context: ./vite-project
