name: test

on:
  workflow_call:
    secrets:
      KUBECONTENT:
        required: true
jobs:
  deployment:
    if: ${{ startsWith(github.ref, 'refs/heads/deployment/') || github.ref == 'refs/heads/main'  }}
    runs-on: [self-hosted]
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Get version
        id: version
        run: |
          if [[ -n "$GITHUB_REF" && "$GITHUB_REF" == "refs/tags/"* ]]; then
            echo "tag version"
            echo "::set-output name=version::${GITHUB_REF/refs\/tags\//}"
          else
            echo "commit version"
            echo "::set-output name=version::${{ github.sha }}"
          fi

      - name: Build nad Push Migrator
        run: |
          docker build -t gitdatateam/migrator:${{ steps.version.outputs.version }} -f ./docker/migrator.Dockerfile .
          docker push gitdatateam/migrator:${{ steps.version.outputs.version }}

      - name: Build and Push Gateway
        run: |
          docker build -t gitdatateam/gateway:${{ steps.version.outputs.version }} -f ./docker/gateway.Dockerfile .
          docker push gitdatateam/gateway:${{ steps.version.outputs.version }}

      - name: Build and Push GitdataAuth
        run: |
          docker build -t gitdatateam/gitdata-auth:${{ steps.version.outputs.version }} -f ./docker/auth.Dockerfile .
          docker push gitdatateam/gitdata-auth:${{ steps.version.outputs.version }}
